# Generated by Django 5.0.2 on 2024-02-13 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='question_text',
            new_name='expense',
        ),
    ]
