# Generated by Django 5.0.2 on 2024-02-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_question_text_expense_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='expense',
            name='pub_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
