# Generated by Django 5.0.2 on 2024-02-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_expense_expense_name_expense_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('markets', 'Markets'), ('pharmacy', 'Pharmacy'), ('entertainment', 'Entertainment'), ('bookstore', 'Bookstore'), ('electronics and gadgets', 'Electronics and gadgets'), ('beauty', 'Beauty'), ('wellness', 'Wellness')], default='-', max_length=100),
        ),
    ]
