# Generated by Django 4.2.3 on 2024-03-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('markets', 'Markets'), ('pharmacy', 'Pharmacy'), ('entertainment', 'Entertainment'), ('bookstore', 'Bookstore'), ('electronics and gadgets', 'Electronics and gadgets'), ('appliances', 'Appliances'), ('beauty', 'Beauty'), ('wellness', 'Wellness')], max_length=100),
        ),
    ]
